services:
  - type: web
    name: flask-beautiful-website
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 wsgi:app
    envVars:
      - key: SECRET_KEY
        value: your_production_secret_key_here
        sync: false
    autoDeploy: true
    repo: your-github-username/your-repo-name
    branch: main
